### ISSUE TITLE
AssetType

### ISSUE THREAD

**Issue by paschal533** [idriss-crypto/ts-library#41]
I tried to import the AssetType this way

```
import { AssetType } from "idriss-crypto/lib/types/assetType";
```

but I'm getting this error

```
Module not found: Package path ./lib/types/assetType is not exported from package
```

**Comment by paschal533** [comment]
I also tried executing the code this way

```
const transactionReceipt = await idriss.transferToIDriss(
          "hello@idriss.xyz",
          {
              network: "evm",
              coin: "MATIC",
              walletTag: "Metamask ETH"
          },
          {
              type: 1,
              amount: 150,
              assetContractAddress: "0x995945Fb74e0f8e345b3f35472c3e07202Eb38Ac"
          },
          "hello dear"
          )

```
but I got an error saying `invalid address`

By the way, shouldn't there be an option to specify the signer of the transaction?

**Comment by lennardevertz** [comment]
Hi @paschal533 
This library is not exporting `AssetType`. You can follow this schema:
```
enum AssetType {
   Native = 0,
   ERC20 = 1,
   ERC721 = 2,
   ERC1155 = 3
}
```

The signer of your transaction is provided in the contstructor when initializing idriss and depends on your setup: 
```
idriss = new IdrissCrypto(web3: Web3|Promise<Web3>, registryWeb3: Web3|Promise<Web3>, connectionOptions: ConnectionOptions)
```

**Comment by lennardevertz** [comment]
And the `invalid address` error is likely thrown because your token address isn't a valid ERC20 contract address. It is actually a wallet address. So the token params you want to provide should be
```
{
     type: AssetType,
     amount: Number,
     assetContractAddress: <Asset Contract Address>
}
```

**Comment by lennardevertz** [comment]
Closed due to inactivity
